export default {
    light: {
        switcherTrackColorOn: '#81b0ff',
        switcherTrackColorOff: '#767577',
        switcherThumbColorOn: '#f5dd4b',
        switcherThumbColorOff: '#f4f3f4',
        switcherIosBackgroundColor: '#3e3e3e',
        homeBackgroundColor: '#FFF',
        headerBackgroundColor: '#273FAD',
        headerTextColor: '#FFF',
        taskTitleColor: '#3D3D4D',
        taskMarkerBorderColor: '#3D3D4D',
        taskTextColor: '#3D3D4D',
        taskButtonDoneBackgroundColor: 'rgba(25, 61, 223, 0.1)',
        taskMarkerDoneBackgroundColor: '#273FAD',
        taskTextDoneColor: '#A09CB1',
        inputColor: '#A09CB1',
        inputPlaceholderColor: '#A09CB1',
        inputContainerBackgroundColor: '#F5F4F8',
        inputBackgroundColor: '#F5F4F8',
        inputIOSShadowColor: '#000',
        inputAddButtonBackgroundColor: '#3FAD27',
    },
    dark: {
        switcherTrackColorOn: '#212136',
        switcherTrackColorOff: '#767577',
        switcherThumbColorOn: '#565BFF',
        switcherThumbColorOff: '#f4f3f4',
        switcherIosBackgroundColor: '#212136',
        homeBackgroundColor: '#10101E',
        headerBackgroundColor: '#191932',
        headerTextColor: '#E1E1E6',
        taskTitleColor: '#565BFF',
        taskMarkerBorderColor: '#565BFF',
        taskTextColor: '#E1E1E6',
        taskButtonDoneBackgroundColor: 'rgba(33, 33, 54, 0.3)',
        taskMarkerDoneBackgroundColor: '#565BFF',
        taskTextDoneColor: 'rgba(225, 225, 230, 0.6)',
        inputColor: '#E1E1E6',
        inputPlaceholderColor: '#E1E1E6',
        inputContainerBackgroundColor: '#212136',
        inputBackgroundColor: '#212136',
        inputIOSShadowColor: '#000',
        inputAddButtonBackgroundColor: '#565BFF',
    },
};